//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restautrant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LKSN2018Entities1 : DbContext
    {
        public LKSN2018Entities1()
            : base("name=LKSN2018Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MsEmployee> MsEmployee { get; set; }
        public virtual DbSet<MsMember> MsMember { get; set; }
        public virtual DbSet<MsMenu> MsMenu { get; set; }
        public virtual DbSet<orderDetail> orderDetail { get; set; }
        public virtual DbSet<OrderHeader> OrderHeader { get; set; }
    }
}
