//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restautrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int Id { get; set; }
        public string Orderid { get; set; }
        public Nullable<int> Menuid { get; set; }
        public int Qty { get; set; }
        public string Status { get; set; }
    
        public virtual MsMenu MsMenu { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
