//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restautrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderHeader()
        {
            this.orderDetail = new HashSet<orderDetail>();
        }
    
        public string Id { get; set; }
        public string Employeeid { get; set; }
        public Nullable<int> Memberid { get; set; }
        public System.DateTime Date { get; set; }
        public string PaymentType { get; set; }
        public string CardNumber { get; set; }
        public string Bank { get; set; }
    
        public virtual MsEmployee MsEmployee { get; set; }
        public virtual MsMember MsMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderDetail> orderDetail { get; set; }
    }
}
